### ISSUE TITLE
WIN key down partially reveals taskbar

### ISSUE THREAD

**Issue by MrCruesliPants** [LuisThiamNye/ButteryTaskbar2#13]
I have migrated from version 1, thank you for this update!

In version 2, when pressing down the Windows key (without lifting the key yet), the taskbar gets partially revealed. One can even mouse over the taskbar to fully reveal it, all while pressing the WIN key. From the description, I understand that this is intended behavior. However, this is causing issues when using other keyboard shortcuts that involve the Windows key. 

For example, when using CTRL+WIN+right to switch to next virtual desktop (Windows default that can't be changed to my knowledge), the partially revealed taskbar briefly pops up, creating a distracting flashing animation. 

Is this something you would consider addressing, @LuisThiamNye? Your tool is absolutely awesome, but the flashes when changing desktops (I do this a lot), makes the tool almost unusable for me 😟

**Comment by LuisThiamNye** [comment]
> pressing down the Windows key (without lifting the key yet), the taskbar gets partially revealed

I think, if I remember right, that I landed on this design decision because I found that it increased the reliability of the tool. In some cases I was encountering problems like where the taskbar would show but be completely transparent (an issue reported in version 1) and so some tricks were needed to get it to work well. I've forgotten the details though, but I'm sure there was a reason why it was useful to show the taskbar before the start menu opens.

As for the flashing, I don't notice this myself. I'm on Windows 11 — maybe you're on Windows 10 and the situation is different. I don't have any good solutions for you. Windows is just awful.

If you're saying the taskbar actually pops up (making the icons visible) then that is weird, unless perhaps an icon is flashing orange.

**Comment by MrCruesliPants** [comment]
Thanks for the reply! I'm indeed on Windows 10. I was able to reduce the visual distraction of the pop-ins by disabling some things on the taskbar ("search highlights"...).

I will close the issue. It's a bit unfortunate that I can't easily compile Buttery Taskbar myself (it seems like I would need to be in the beta for Jai?), but what I would probably try to do for myself is configure the Escape key (or something like F12) to reveal the taskbar instead, just to completely avoid revealing the taskbar when I'm using the WIN key as part of other shortcuts.
