### ISSUE TITLE
Can you rewrite it in a more accessible programming language?

### ISSUE THREAD

**Issue by astrolemonade** [LuisThiamNye/ButteryTaskbar2#16]
Hey! This software is absolutely awesome!
Unfortunately, it's written in Jai, a programming language that is not available to the public. That means we cannot contribute, there is no possibility to produce our own executables and also to vet the code.

**Comment by LuisThiamNye** [comment]
I'm glad you appreciate the software.

If the open-source thing matters to you, then you can look at a previous version which was written in the Odin programming language:

https://github.com/LuisThiamNye/ButteryTaskbar2/tree/a79ccdb2d927c850483bebdae9d268adf578ce68

Also, the original version was written in C#.

Jai is most similar (syntactically) to Odin, so you could rewrite the current version in Odin, but you would have to make subtitutions for some of Jai's provided modules that I use. It's a small project, so not a large undertaking and you could make whatever modifications you want.

I am not going to rewrite the project back to Odin, because there is exactly no benefit to me doing that. People don't contribute, and I probably would not accept contributions anyway. Only very rarely would I act on something like a feature request but normally I only make changes to suit my needs and my needs only — because, after all, I get paid exactly nothing for this work.
