### ISSUE TITLE
Add a toggle for scroll wheel activation 

### ISSUE THREAD

**Issue by Ryah** [LuisThiamNye/ButteryTaskbar2#3]
I know I'm probably an edge case, but I have a super ultrawide monitor (5120x1440p) and often play games in 1440p windowed mode to have discord or whatever else open on the sides. This sometimes results in me looking down and scrolling (to change weapon/tool) and the taskbar/start menu appearing. A keybind or launch option to disable this without disabling the functionality of Buttery Taskbar would be very helpful.

**Comment by LuisThiamNye** [comment]
Thank you for reporting your use case. In the meantime, the [previous version 2.0.0](https://github.com/LuisThiamNye/ButteryTaskbar2/releases/tag/2.0.0) does not have this feature but should otherwise work the same.

The right solution depends on how often the scroll feature is useful to you, if ever. Some ideas:
- Hard-coded key binding (I am concerned about consuming additional global key bindings that the user might want to use for other functions, but it might be okay).
- User-configurable key binding.
- An option to disable the feature from a tray icon menu.
- Configuration file.
- Releasing two separate executables: one with and one without the feature (which is essentially the case right now).

Any thoughts?

**Comment by Ryah** [comment]
If you're planning on adding more features that may need to be toggled on or off, then a config file is a pretty good idea. 

Otherwise, a user-configurable config key binding or an option to disable it from a tray icon menu may be best.

**Comment by LuisThiamNye** [comment]
Well the question is whether it is useful to toggle it without the inconvenience of editing a file and restarting the program. In other words, is the feature _ever_ useful to you? I can’t tell if it is just a thing that is occasionally inconvenient but okay otherwise, or if it is something you want permanently disabled.

**Comment by LuisThiamNye** [comment]
The new version has a settings window where you can disable the scroll feature.

https://github.com/LuisThiamNye/ButteryTaskbar2/releases

If you encounter any further issues with the new release, please do write back.

**Comment by JZ6** [comment]
any chance we can set a custom keybind for this? I would like to turn it off for certain games, thanks
