### ISSUE TITLE
Feature Request 2: Hover to reveal taskbar

### ISSUE THREAD

**Issue by pr0cqd** [LuisThiamNye/ButteryTaskbar2#6]
Hey first of all thanks for such an improved Taskbar Experience. The only thing that id want to see is the Feature to "Hover over the taskbar" to reveal it.  
My Problem with the Scroll Option is that: 
1) It opens the start menu 
2) Its another button press 

Hovering over taskbar to reveal it negates these "Problems" and makes it generally quicker. As I said would love to see that option added under the Settings. That would make it the perfect Taskbar Extension that ive been looking for

**Comment by LuisThiamNye** [comment]
Is that not the default auto-hide behaviour in Windows? The whole point of Buttery Taskbar was to provide an alternative to that.

**Comment by pr0cqd** [comment]
> Is that not the default auto-hide behaviour in Windows? The whole point of Buttery Taskbar was to provide an alternative to that.

Yes! xD ^^
My problem ist that Windows leaves a thin white line under the taskbar icons even after the taskbar disappears ([see picture](https://imgur.com/X3p3vtD))
Your Extension fixes that but in return removes the "hover to reveal taskbar" feature.

**Comment by effree** [comment]
I like this suggestion.  I use Droptop4 which has a toggle for opening the system tray.  but when using the default windows autohide it doesn't function.  Using your app it works better because it has the ability to instant show the taskbar.  Which is the cause of the droptop issue.  The windows animation screws up the timing of their app.  But i still want to be able to go to the bottom of the screen to show the taskbar, preferably without the start menu being open automatically.

**Comment by hilfing** [comment]
I also want this feature

**Comment by Theo-user** [comment]
Me too. Thanks

**Comment by LuisThiamNye** [comment]
@effree
> Using your app it works better because it has the ability to instant show the taskbar.

I don’t think my program can directly “instant show” the taskbar (if you mean show the full taskbar without any animation). I think the skipping of the animation is an effect of opening the Start Menu.

**Comment by jobs-git** [comment]
This should be closed, that is already the default behavior of taskbar, if you want to hide the line, it might be a different program you are looking for.
